/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  MyTodo as MyTodo
} from './components/my-todo/my-todo';

declare global {
  interface HTMLMyTodoElement extends MyTodo, HTMLStencilElement {
  }
  var HTMLMyTodoElement: {
    prototype: HTMLMyTodoElement;
    new (): HTMLMyTodoElement;
  };
  interface HTMLElementTagNameMap {
    "my-todo": HTMLMyTodoElement;
  }
  interface ElementTagNameMap {
    "my-todo": HTMLMyTodoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-todo": JSXElements.MyTodoAttributes;
    }
  }
  namespace JSXElements {
    export interface MyTodoAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  TodoInput as TodoInput
} from './components/todo-input/todo-input';

declare global {
  interface HTMLTodoInputElement extends TodoInput, HTMLStencilElement {
  }
  var HTMLTodoInputElement: {
    prototype: HTMLTodoInputElement;
    new (): HTMLTodoInputElement;
  };
  interface HTMLElementTagNameMap {
    "todo-input": HTMLTodoInputElement;
  }
  interface ElementTagNameMap {
    "todo-input": HTMLTodoInputElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "todo-input": JSXElements.TodoInputAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoInputAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  TodoItem as TodoItem
} from './components/todo-item/todo-item';

declare global {
  interface HTMLTodoItemElement extends TodoItem, HTMLStencilElement {
  }
  var HTMLTodoItemElement: {
    prototype: HTMLTodoItemElement;
    new (): HTMLTodoItemElement;
  };
  interface HTMLElementTagNameMap {
    "todo-item": HTMLTodoItemElement;
  }
  interface ElementTagNameMap {
    "todo-item": HTMLTodoItemElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "todo-item": JSXElements.TodoItemAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoItemAttributes extends HTMLAttributes {
      checked?: boolean;
      index?: number;
      text?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
